### ISSUE TITLE
Can not join meetings from calendar "Join" button

### ISSUE THREAD

**Issue by HarlemSquirrel** [flathub/us.zoom.Zoom#210]
When logged in to Zoom, clicking the join button results in a window with only a white screen. I have to close this window and open the meeting link in my browser to be able to join the meeting. 

Zoom flatpak 5.3.465578.0920
Fedora 32
GNOME 3.36.6 on x11

**Comment by ericp-mrel** [comment]
This is a Zoom issue, not an issue with the flatpak. I've experienced this same issue using the deb version and have reported it to them, but I don't know if they're even fixing it since I haven't heard back from them.

I'd suggest reporting this to Zoom and maybe if they see more people reporting this as an issue they'll fix it faster. Otherwise, you just have to use the meetings tab and use the join button from there.

**Comment by HarlemSquirrel** [comment]
OK, thanks
